import type { Roster } from "./types";

/**
 * Stats, in order: Batting, Bowling, Fielding, Power, Composure, Experience.
 * Affinity cycle: willow ▸ pace ▸ spin ▸ willow.
 */
export const cricket: Roster = {
  cards: [
    /* ------------------------------ legends ------------------------------ */
    {
      id: "tendulkar",
      name: "Sachin Tendulkar",
      title: "One hundred hundreds",
      emoji: "🐐",
      affinity: "willow",
      rarity: "legend",
      stats: [10, 3, 7, 9, 10, 9],
      ability: {
        kind: "finisher",
        value: 55,
        name: "The Straight Drive",
        text: "Below a third of your health, deals 55% more damage.",
      },
    },
    {
      id: "warne",
      name: "Shane Warne",
      title: "Ball of the Century",
      emoji: "🌀",
      affinity: "spin",
      rarity: "legend",
      stats: [3, 10, 8, 8, 10, 9],
      ability: {
        kind: "pierce",
        value: 40,
        name: "The Gatting Ball",
        text: "Ignores 40% of whatever is defending.",
      },
    },

    /* ------------------------------- epics ------------------------------- */
    {
      id: "kohli",
      name: "Virat Kohli",
      title: "King of the run chase",
      emoji: "👑",
      affinity: "willow",
      rarity: "epic",
      stats: [10, 2, 9, 8, 7, 7],
      ability: {
        kind: "drain",
        value: 40,
        name: "The Chase",
        text: "Heals 40% of the damage it deals.",
      },
    },
    {
      id: "bumrah",
      name: "Jasprit Bumrah",
      title: "That run-up",
      emoji: "🎯",
      affinity: "pace",
      rarity: "epic",
      stats: [2, 10, 7, 9, 9, 6],
      ability: {
        kind: "pierce",
        value: 35,
        name: "The Yorker",
        text: "Ignores 35% of whatever is defending.",
      },
    },
    {
      id: "dhoni",
      name: "MS Dhoni",
      title: "Captain Cool",
      emoji: "🧊",
      affinity: "willow",
      rarity: "epic",
      stats: [8, 1, 10, 9, 10, 5],
      ability: {
        kind: "finisher",
        value: 50,
        name: "Finish It in the 49th",
        text: "Below a third of your health, deals 50% more damage.",
      },
    },

    /* ------------------------------- rares ------------------------------- */
    {
      id: "rohit",
      name: "Rohit Sharma",
      title: "Three double hundreds",
      emoji: "🎳",
      affinity: "willow",
      rarity: "rare",
      stats: [9, 2, 6, 9, 6, 6],
      ability: {
        kind: "surge",
        value: 3,
        name: "The Pull Shot",
        text: "Adds 3 to the stat it attacks with.",
      },
    },
    {
      id: "jadeja",
      name: "Ravindra Jadeja",
      title: "Sir",
      emoji: "🗡️",
      affinity: "spin",
      rarity: "rare",
      stats: [6, 8, 10, 5, 5, 4],
      ability: {
        kind: "riposte",
        value: 35,
        name: "The Direct Hit",
        text: "Sends 35% of the damage it takes straight back.",
      },
    },
    {
      id: "stokes",
      name: "Ben Stokes",
      title: "Headingley, 2019",
      emoji: "🔥",
      affinity: "pace",
      rarity: "rare",
      stats: [7, 7, 7, 8, 5, 4],
      ability: {
        kind: "rally",
        value: 6,
        name: "One Wicket Left",
        text: "Heals 6 the moment it is turned over.",
      },
    },
    {
      id: "rashid",
      name: "Rashid Khan",
      title: "You cannot read him",
      emoji: "🔮",
      affinity: "spin",
      rarity: "rare",
      stats: [4, 10, 7, 6, 6, 5],
      ability: {
        kind: "guard",
        value: 30,
        name: "The Googly",
        text: "Cuts incoming damage by 30%.",
      },
    },

    /* ------------------------------ commons ------------------------------ */
    {
      id: "pandya",
      name: "Hardik Pandya",
      title: "Sixes and seam-up",
      emoji: "💥",
      affinity: "pace",
      rarity: "common",
      stats: [6, 6, 6, 8, 4, 3],
      ability: {
        kind: "surge",
        value: 2,
        name: "Over Long-On",
        text: "Adds 2 to the stat it attacks with.",
      },
    },
    {
      id: "buttler",
      name: "Jos Buttler",
      title: "Behind and in front of the stumps",
      emoji: "🧤",
      affinity: "willow",
      rarity: "common",
      stats: [8, 1, 8, 9, 4, 3],
      ability: {
        kind: "drain",
        value: 35,
        name: "The Ramp",
        text: "Heals 35% of the damage it deals.",
      },
    },
    {
      id: "starc",
      name: "Mitchell Starc",
      title: "Left-arm, 150kph",
      emoji: "🏹",
      affinity: "pace",
      rarity: "common",
      stats: [3, 9, 5, 8, 4, 4],
      ability: {
        kind: "pierce",
        value: 30,
        name: "Reverse Swing",
        text: "Ignores 30% of whatever is defending.",
      },
    },
    {
      id: "ashwin",
      name: "Ravichandran Ashwin",
      title: "Six ways to bowl one ball",
      emoji: "🎛️",
      affinity: "spin",
      rarity: "common",
      stats: [4, 9, 5, 5, 6, 4],
      ability: {
        kind: "guard",
        value: 30,
        name: "The Carrom Ball",
        text: "Cuts incoming damage by 30%.",
      },
    },
    {
      id: "rabada",
      name: "Kagiso Rabada",
      title: "Hostile from ball one",
      emoji: "⚡",
      affinity: "pace",
      rarity: "common",
      stats: [2, 9, 6, 9, 4, 3],
      ability: {
        kind: "riposte",
        value: 30,
        name: "The Bouncer",
        text: "Sends 30% of the damage it takes straight back.",
      },
    },
  ],

  events: [
    {
      id: "powerplay",
      name: "Powerplay",
      text: "Two men out. Everything hurts 50% more.",
      kind: "damage_up",
      value: 50,
      emoji: "🎯",
    },
    {
      id: "rain-delay",
      name: "Rain Delay",
      text: "Covers on, revised target. Damage down 40%.",
      kind: "damage_down",
      value: 40,
      emoji: "🌧️",
    },
    {
      id: "dead-deck",
      name: "A Dead Deck",
      text: "Nothing off the surface. Everything defends 2 better.",
      kind: "defense_up",
      value: 2,
      emoji: "🟫",
    },
    {
      id: "drinks",
      name: "Drinks Break",
      text: "Gloves off, ice down the neck. Both sides recover 4.",
      kind: "heal_both",
      value: 4,
      emoji: "🥤",
    },
    {
      id: "pink-ball",
      name: "Day-Night Test",
      text: "Under lights with a pink ball, nobody's specialism counts.",
      kind: "no_affinity",
      value: 0,
      emoji: "🌗",
    },
    {
      id: "third-umpire",
      name: "Upstairs",
      text: "Everything is under review. No signature shots this over.",
      kind: "abilities_off",
      value: 0,
      emoji: "📺",
    },
  ],
};
