import type { Roster } from "./types";

/**
 * Stats, in order: Pace, Shooting, Passing, Dribbling, Defending, Physical.
 * Affinity cycle: attack ▸ midfield ▸ defence ▸ attack.
 */
export const football: Roster = {
  cards: [
    /* ------------------------------ legends ------------------------------ */
    {
      id: "messi",
      name: "Lionel Messi",
      title: "Eight Ballons d'Or",
      emoji: "🐐",
      affinity: "attack",
      rarity: "legend",
      stats: [8, 10, 10, 10, 3, 7],
      ability: {
        kind: "surge",
        value: 3,
        name: "The Left Foot",
        text: "Adds 3 to the stat it attacks with.",
      },
    },
    {
      id: "ronaldo",
      name: "Cristiano Ronaldo",
      title: "Scores in every league he touches",
      emoji: "🚀",
      affinity: "attack",
      rarity: "legend",
      stats: [9, 10, 7, 8, 4, 10],
      ability: {
        kind: "finisher",
        value: 55,
        name: "Siuuu",
        text: "Below a third of your health, deals 55% more damage.",
      },
    },

    /* ------------------------------- epics ------------------------------- */
    {
      id: "mbappe",
      name: "Kylian Mbappé",
      title: "Ten metres and it's over",
      emoji: "💨",
      affinity: "attack",
      rarity: "epic",
      stats: [10, 9, 6, 9, 2, 7],
      ability: {
        kind: "pierce",
        value: 35,
        name: "In Behind",
        text: "Ignores 35% of whatever is defending.",
      },
    },
    {
      id: "zidane",
      name: "Zinedine Zidane",
      title: "Glasgow, 2002",
      emoji: "🎩",
      affinity: "midfield",
      rarity: "epic",
      stats: [6, 8, 10, 10, 4, 5],
      ability: {
        kind: "riposte",
        value: 40,
        name: "La Roulette",
        text: "Sends 40% of the damage it takes straight back.",
      },
    },
    {
      id: "maldini",
      name: "Paolo Maldini",
      title: "A tackle is a last resort",
      emoji: "🧱",
      affinity: "defence",
      rarity: "epic",
      stats: [8, 3, 8, 5, 10, 9],
      ability: {
        kind: "guard",
        value: 40,
        name: "Read It Early",
        text: "Cuts incoming damage by 40%.",
      },
    },

    /* ------------------------------- rares ------------------------------- */
    {
      id: "haaland",
      name: "Erling Haaland",
      title: "Lives in the six-yard box",
      emoji: "🤖",
      affinity: "attack",
      rarity: "rare",
      stats: [8, 10, 4, 6, 2, 8],
      ability: {
        kind: "finisher",
        value: 50,
        name: "One Touch",
        text: "Below a third of your health, deals 50% more damage.",
      },
    },
    {
      id: "de-bruyne",
      name: "Kevin De Bruyne",
      title: "Sees the pass before you do",
      emoji: "🎯",
      affinity: "midfield",
      rarity: "rare",
      stats: [6, 7, 10, 6, 4, 5],
      ability: {
        kind: "surge",
        value: 3,
        name: "The Whipped Cross",
        text: "Adds 3 to the stat it attacks with.",
      },
    },
    {
      id: "modric",
      name: "Luka Modrić",
      title: "Still there in the 118th minute",
      emoji: "🧭",
      affinity: "midfield",
      rarity: "rare",
      stats: [6, 6, 9, 8, 5, 4],
      ability: {
        kind: "drain",
        value: 35,
        name: "Keeps the Ball",
        text: "Heals 35% of the damage it deals.",
      },
    },
    {
      id: "van-dijk",
      name: "Virgil van Dijk",
      title: "Does not get turned",
      emoji: "🗿",
      affinity: "defence",
      rarity: "rare",
      stats: [7, 3, 6, 4, 10, 8],
      ability: {
        kind: "guard",
        value: 35,
        name: "The Recovery Run",
        text: "Cuts incoming damage by 35%.",
      },
    },

    /* ------------------------------ commons ------------------------------ */
    {
      id: "vinicius",
      name: "Vinícius Júnior",
      title: "Straight at the full-back",
      emoji: "🕺",
      affinity: "attack",
      rarity: "common",
      stats: [10, 7, 5, 9, 1, 1],
      ability: {
        kind: "pierce",
        value: 30,
        name: "One-on-One",
        text: "Ignores 30% of whatever is defending.",
      },
    },
    {
      id: "bellingham",
      name: "Jude Bellingham",
      title: "Arrives in the box late",
      emoji: "🌟",
      affinity: "midfield",
      rarity: "common",
      stats: [6, 7, 6, 6, 4, 4],
      ability: {
        kind: "rally",
        value: 5,
        name: "Hey Jude",
        text: "Heals 5 the moment it is turned over.",
      },
    },
    {
      id: "ramos",
      name: "Sergio Ramos",
      title: "93:20",
      emoji: "🦁",
      affinity: "defence",
      rarity: "common",
      stats: [5, 4, 5, 3, 9, 7],
      ability: {
        kind: "riposte",
        value: 35,
        name: "Up for the Corner",
        text: "Sends 35% of the damage it takes straight back.",
      },
    },
    {
      id: "kante",
      name: "N'Golo Kanté",
      title: "There are two of him",
      emoji: "🐜",
      affinity: "midfield",
      rarity: "common",
      stats: [6, 2, 6, 5, 9, 5],
      ability: {
        kind: "guard",
        value: 30,
        name: "Wins It Back",
        text: "Cuts incoming damage by 30%.",
      },
    },
    {
      id: "neuer",
      name: "Manuel Neuer",
      title: "A defender who is allowed hands",
      emoji: "🧤",
      affinity: "defence",
      rarity: "common",
      stats: [4, 1, 6, 3, 10, 9],
      ability: {
        kind: "riposte",
        value: 30,
        name: "The Sweeper Keeper",
        text: "Sends 30% of the damage it takes straight back.",
      },
    },
  ],

  events: [
    {
      id: "added-time",
      name: "Eight Minutes Added",
      text: "Everyone is throwing bodies forward. Damage up 50%.",
      kind: "damage_up",
      value: 50,
      emoji: "⏱️",
    },
    {
      id: "offside",
      name: "The Flag Goes Up",
      text: "Half of it gets chalked off. Damage down 40%.",
      kind: "damage_down",
      value: 40,
      emoji: "🚩",
    },
    {
      id: "low-block",
      name: "Parked the Bus",
      text: "Ten behind the ball. Everything defends 2 better.",
      kind: "defense_up",
      value: 2,
      emoji: "🚌",
    },
    {
      id: "half-time",
      name: "Half Time",
      text: "Oranges and a rollicking. Both sides recover 4.",
      kind: "heal_both",
      value: 4,
      emoji: "🍊",
    },
    {
      id: "shootout",
      name: "Penalty Shootout",
      text: "From twelve yards nobody's position means anything.",
      kind: "no_affinity",
      value: 0,
      emoji: "🥅",
    },
    {
      id: "on-a-booking",
      name: "On a Booking",
      text: "One more and you're off, so nobody tries anything clever.",
      kind: "abilities_off",
      value: 0,
      emoji: "🟨",
    },
  ],
};
