import type { Roster } from "./types";

/**
 * Stats, in order: Ninjutsu, Taijutsu, Genjutsu, Chakra, Speed, Intellect.
 * Affinity cycle: ninjutsu ▸ genjutsu ▸ taijutsu ▸ ninjutsu.
 */
export const naruto: Roster = {
  cards: [
    /* ------------------------------ legends ------------------------------ */
    {
      id: "naruto",
      name: "Naruto Uzumaki",
      title: "Seventh Hokage",
      emoji: "🍥",
      affinity: "ninjutsu",
      rarity: "legend",
      stats: [10, 8, 3, 10, 9, 8],
      ability: {
        kind: "rally",
        value: 7,
        name: "Nine-Tails Chakra",
        text: "Heals 7 the moment it is turned over.",
      },
    },
    {
      id: "itachi",
      name: "Itachi Uchiha",
      title: "He was on your side the whole time",
      emoji: "🪶",
      affinity: "genjutsu",
      rarity: "legend",
      stats: [8, 6, 10, 6, 9, 9],
      ability: {
        kind: "riposte",
        value: 45,
        name: "Tsukuyomi",
        text: "Sends 45% of the damage it takes straight back.",
      },
    },

    /* ------------------------------- epics ------------------------------- */
    {
      id: "sasuke",
      name: "Sasuke Uchiha",
      title: "The last Uchiha",
      emoji: "⚡",
      affinity: "genjutsu",
      rarity: "epic",
      stats: [9, 7, 8, 7, 8, 4],
      ability: {
        kind: "pierce",
        value: 35,
        name: "Chidori",
        text: "Ignores 35% of whatever is defending.",
      },
    },
    {
      id: "kakashi",
      name: "Kakashi Hatake",
      title: "A thousand jutsu copied",
      emoji: "📕",
      affinity: "ninjutsu",
      rarity: "epic",
      stats: [9, 7, 6, 6, 7, 8],
      ability: {
        kind: "riposte",
        value: 40,
        name: "Copy Ninja",
        text: "Sends 40% of the damage it takes straight back.",
      },
    },
    {
      id: "might-guy",
      name: "Might Guy",
      title: "No ninjutsu, no problem",
      emoji: "🟢",
      affinity: "taijutsu",
      rarity: "epic",
      stats: [4, 10, 2, 10, 10, 7],
      ability: {
        kind: "finisher",
        value: 60,
        name: "Eight Inner Gates",
        text: "Below a third of your health, deals 60% more damage.",
      },
    },

    /* ------------------------------- rares ------------------------------- */
    {
      id: "gaara",
      name: "Gaara",
      title: "Kazekage of the Sand",
      emoji: "🏜️",
      affinity: "ninjutsu",
      rarity: "rare",
      stats: [9, 4, 3, 9, 5, 8],
      ability: {
        kind: "guard",
        value: 40,
        name: "Shield of Sand",
        text: "Cuts incoming damage by 40%.",
      },
    },
    {
      id: "rock-lee",
      name: "Rock Lee",
      title: "Hard work beats talent",
      emoji: "👊",
      affinity: "taijutsu",
      rarity: "rare",
      stats: [2, 10, 1, 9, 10, 6],
      ability: {
        kind: "surge",
        value: 3,
        name: "Drop the Weights",
        text: "Adds 3 to the stat it attacks with.",
      },
    },
    {
      id: "jiraiya",
      name: "Jiraiya",
      title: "The Toad Sage",
      emoji: "🐸",
      affinity: "ninjutsu",
      rarity: "rare",
      stats: [9, 6, 5, 7, 5, 6],
      ability: {
        kind: "surge",
        value: 3,
        name: "Rasengan",
        text: "Adds 3 to the stat it attacks with.",
      },
    },
    {
      id: "tsunade",
      name: "Tsunade",
      title: "Fifth Hokage",
      emoji: "💠",
      affinity: "taijutsu",
      rarity: "rare",
      stats: [7, 9, 3, 8, 4, 7],
      ability: {
        kind: "drain",
        value: 45,
        name: "Byakugō Seal",
        text: "Heals 45% of the damage it deals.",
      },
    },

    /* ------------------------------ commons ------------------------------ */
    {
      id: "shikamaru",
      name: "Shikamaru Nara",
      title: "Two hundred moves ahead, reluctantly",
      emoji: "🦌",
      affinity: "genjutsu",
      rarity: "common",
      stats: [5, 3, 6, 4, 5, 10],
      ability: {
        kind: "guard",
        value: 35,
        name: "Shadow Possession",
        text: "Cuts incoming damage by 35%.",
      },
    },
    {
      id: "hinata",
      name: "Hinata Hyūga",
      title: "Gentle Fist",
      emoji: "🤍",
      affinity: "taijutsu",
      rarity: "common",
      stats: [4, 8, 2, 5, 7, 7],
      ability: {
        kind: "drain",
        value: 35,
        name: "Twin Lion Fists",
        text: "Heals 35% of the damage it deals.",
      },
    },
    {
      id: "neji",
      name: "Neji Hyūga",
      title: "You are within my field of divination",
      emoji: "👁️",
      affinity: "taijutsu",
      rarity: "common",
      stats: [4, 9, 2, 5, 7, 6],
      ability: {
        kind: "pierce",
        value: 35,
        name: "Eight Trigrams",
        text: "Ignores 35% of whatever is defending.",
      },
    },
    {
      id: "sakura",
      name: "Sakura Haruno",
      title: "Medical ninja, monstrous strength",
      emoji: "🌸",
      affinity: "ninjutsu",
      rarity: "common",
      stats: [6, 8, 4, 4, 5, 6],
      ability: {
        kind: "rally",
        value: 6,
        name: "Mystical Palm",
        text: "Heals 6 the moment it is turned over.",
      },
    },
    {
      id: "kurenai",
      name: "Kurenai Yūhi",
      title: "The Leaf's genjutsu specialist",
      emoji: "🌫️",
      affinity: "genjutsu",
      rarity: "common",
      stats: [4, 4, 9, 5, 5, 6],
      ability: {
        kind: "guard",
        value: 30,
        name: "Demonic Illusion",
        text: "Cuts incoming damage by 30%.",
      },
    },
  ],

  events: [
    {
      id: "tailed-beast",
      name: "Tailed Beast Rampage",
      text: "Something very large is awake. Damage up 50%.",
      kind: "damage_up",
      value: 50,
      emoji: "🦊",
    },
    {
      id: "substitution",
      name: "Substitution Jutsu",
      text: "You hit a log. Both of you. Damage down 40%.",
      kind: "damage_down",
      value: 40,
      emoji: "🪵",
    },
    {
      id: "barrier",
      name: "Four Violet Flames",
      text: "A barrier over the whole field. Everything defends 2 better.",
      kind: "defense_up",
      value: 2,
      emoji: "🟪",
    },
    {
      id: "medical-corps",
      name: "The Medical Corps",
      text: "Green hands on both of you. Both recover 4.",
      kind: "heal_both",
      value: 4,
      emoji: "💚",
    },
    {
      id: "kamui",
      name: "Kamui",
      text: "Half the fight is in another dimension. Specialisms don't connect.",
      kind: "no_affinity",
      value: 0,
      emoji: "🌀",
    },
    {
      id: "sealing-jutsu",
      name: "Sealing Jutsu",
      text: "Chakra locked down. Nobody gets their signature off.",
      kind: "abilities_off",
      value: 0,
      emoji: "📜",
    },
  ],
};
