import type { Question } from "./types";

export const cricket: readonly Question[] = [
  {
    id: "c1",
    prompt: "Who holds the record for the most runs in international cricket?",
    choices: ["Ricky Ponting", "Sachin Tendulkar", "Kumar Sangakkara", "Virat Kohli"],
    answer: 1,
    fact: "Just over 34,000 runs across all three formats.",
  },
  {
    id: "c2",
    prompt: "How many legal deliveries make up a standard over?",
    choices: ["4", "5", "6", "8"],
    answer: 2,
  },
  {
    id: "c3",
    prompt: "Which team won the first Cricket World Cup, in 1975?",
    choices: ["Australia", "England", "West Indies", "India"],
    answer: 2,
    fact: "They won the second one too, in 1979.",
  },
  {
    id: "c4",
    prompt: "Who scored the first double century in a men's ODI?",
    choices: ["Sachin Tendulkar", "Virender Sehwag", "Rohit Sharma", "Chris Gayle"],
    answer: 0,
    fact: "200 not out against South Africa in Gwalior, 2010.",
  },
  {
    id: "c5",
    prompt: "What is the maximum number of overs one bowler may bowl in a 50-over ODI?",
    choices: ["8", "10", "12", "15"],
    answer: 1,
  },
  {
    id: "c6",
    prompt: "Which ground is known as the Home of Cricket?",
    choices: ["The Oval", "Eden Gardens", "Lord's", "the MCG"],
    answer: 2,
  },
  {
    id: "c7",
    prompt: "Who captained India to the 2011 World Cup title?",
    choices: ["Virat Kohli", "Rahul Dravid", "Sourav Ganguly", "MS Dhoni"],
    answer: 3,
    fact: "He finished it himself with a six over long-on.",
  },
  {
    id: "c8",
    prompt: "What does LBW stand for?",
    choices: ["Leg Before Wicket", "Left Bat Wide", "Long Ball Wide", "Leg Bye Wicket"],
    answer: 0,
  },
  {
    id: "c9",
    prompt: "Who has taken the most wickets in Test cricket?",
    choices: ["Shane Warne", "Muttiah Muralitharan", "Anil Kumble", "James Anderson"],
    answer: 1,
    fact: "800 Test wickets, a number nobody has got near since.",
  },
  {
    id: "c10",
    prompt: "How many players from one side are on the field at a time?",
    choices: ["9", "10", "11", "12"],
    answer: 2,
  },
  {
    id: "c11",
    prompt: "Who hit six sixes in an over at the 2007 T20 World Cup?",
    choices: ["Yuvraj Singh", "MS Dhoni", "Chris Gayle", "Shahid Afridi"],
    answer: 0,
    fact: "Off Stuart Broad, and the fifty came in twelve balls.",
  },
  {
    id: "c12",
    prompt: "Which team won the very first IPL title in 2008?",
    choices: ["Chennai Super Kings", "Mumbai Indians", "Rajasthan Royals", "Deccan Chargers"],
    answer: 2,
    fact: "Captained by Shane Warne, off the last ball of the final.",
  },
  {
    id: "c13",
    prompt: "What is it called when a bowler takes three wickets in three consecutive balls?",
    choices: ["A treble", "A hat-trick", "A triple strike", "A trifecta"],
    answer: 1,
  },
  {
    id: "c14",
    prompt: "What is the highest individual score in a Test innings?",
    choices: ["375", "380", "400 not out", "401"],
    answer: 2,
    fact: "Brian Lara, against England in Antigua, 2004.",
  },
  {
    id: "c15",
    prompt: "Which two nations contest The Ashes?",
    choices: [
      "England and South Africa",
      "England and Australia",
      "Australia and New Zealand",
      "India and Pakistan",
    ],
    answer: 1,
  },
  {
    id: "c16",
    prompt: "What colour is the ball in a day-night Test match?",
    choices: ["White", "Pink", "Orange", "Yellow"],
    answer: 1,
  },
  {
    id: "c17",
    prompt: "Who reached 10,000 ODI runs in the fewest innings?",
    choices: ["Sachin Tendulkar", "AB de Villiers", "Virat Kohli", "Ricky Ponting"],
    answer: 2,
    fact: "205 innings, beating Tendulkar's record by fifty-four.",
  },
  {
    id: "c18",
    prompt: "In cricket, what is a duck?",
    choices: [
      "A ball that bounces twice",
      "Being dismissed without scoring",
      "A fielding position",
      "An over with no runs",
    ],
    answer: 1,
  },
  {
    id: "c19",
    prompt: "How long is a cricket pitch, wicket to wicket?",
    choices: ["18 yards", "20 yards", "22 yards", "24 yards"],
    answer: 2,
  },
  {
    id: "c20",
    prompt: "Which country hosted the 2023 ODI World Cup?",
    choices: ["England", "Australia", "India", "South Africa"],
    answer: 2,
  },
  {
    id: "c21",
    prompt: "Which Indian bowler took all ten wickets in a Test innings in 1999?",
    choices: ["Harbhajan Singh", "Anil Kumble", "Javagal Srinath", "Kapil Dev"],
    answer: 1,
    fact: "10 for 74 against Pakistan in Delhi — only the second man ever to do it.",
  },
  {
    id: "c22",
    prompt: "What is a maiden over?",
    choices: [
      "An over with no runs conceded",
      "A bowler's first over ever",
      "An over with a wicket",
      "The first over of an innings",
    ],
    answer: 0,
  },
  {
    id: "c23",
    prompt: "How many runs is a ball that clears the boundary without bouncing worth?",
    choices: ["4", "5", "6", "8"],
    answer: 2,
  },
  {
    id: "c24",
    prompt: "Which fielding position stands directly behind the batter's stumps?",
    choices: ["Gully", "Slip", "Wicketkeeper", "Point"],
    answer: 2,
  },
];
