import type { Question } from "./types";

export const football: readonly Question[] = [
  {
    id: "f1",
    prompt: "Which country has won the most FIFA World Cups?",
    choices: ["Germany", "Italy", "Argentina", "Brazil"],
    answer: 3,
    fact: "Five, and the only side to have played at every tournament.",
  },
  {
    id: "f2",
    prompt: "Which club has won the most European Cup / Champions League titles?",
    choices: ["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"],
    answer: 0,
    fact: "Fifteen, which is more than the next two clubs combined.",
  },
  {
    id: "f3",
    prompt: "Who won the 2022 FIFA World Cup?",
    choices: ["France", "Argentina", "Croatia", "Brazil"],
    answer: 1,
    fact: "3–3 after extra time, settled on penalties in Qatar.",
  },
  {
    id: "f4",
    prompt: "Who has won the most Ballon d'Or awards?",
    choices: ["Cristiano Ronaldo", "Johan Cruyff", "Lionel Messi", "Michel Platini"],
    answer: 2,
    fact: "Eight, the most recent in 2023.",
  },
  {
    id: "f5",
    prompt: "How long is a standard match, before stoppage time?",
    choices: ["80 minutes", "90 minutes", "100 minutes", "120 minutes"],
    answer: 1,
  },
  {
    id: "f6",
    prompt: "Who is the all-time top scorer in men's international football?",
    choices: ["Lionel Messi", "Pelé", "Cristiano Ronaldo", "Ali Daei"],
    answer: 2,
  },
  {
    id: "f7",
    prompt: "In which year was the first World Cup held?",
    choices: ["1922", "1930", "1938", "1950"],
    answer: 1,
    fact: "Uruguay hosted it, and won it.",
  },
  {
    id: "f8",
    prompt: "Which country hosted the 2018 World Cup?",
    choices: ["Brazil", "South Africa", "Russia", "Qatar"],
    answer: 2,
  },
  {
    id: "f9",
    prompt: "Which English club is nicknamed the Red Devils?",
    choices: ["Liverpool", "Arsenal", "Nottingham Forest", "Manchester United"],
    answer: 3,
  },
  {
    id: "f10",
    prompt: "Who scored the Hand of God goal?",
    choices: ["Diego Maradona", "Pelé", "Zinedine Zidane", "Ronaldo Nazário"],
    answer: 0,
    fact: "Then he scored the greatest goal of all time four minutes later.",
  },
  {
    id: "f11",
    prompt: "Which nation won Euro 2020, played in 2021?",
    choices: ["England", "Spain", "Italy", "France"],
    answer: 2,
    fact: "On penalties at Wembley, against the hosts.",
  },
  {
    id: "f12",
    prompt: "How far is the penalty spot from the goal line?",
    choices: ["10 yards", "11 yards", "12 yards", "14 yards"],
    answer: 2,
  },
  {
    id: "f13",
    prompt: "Which stadium is home to FC Barcelona?",
    choices: ["Santiago Bernabéu", "Camp Nou", "San Siro", "Anfield"],
    answer: 1,
  },
  {
    id: "f14",
    prompt: "Who is the all-time top scorer in the Premier League?",
    choices: ["Wayne Rooney", "Harry Kane", "Alan Shearer", "Thierry Henry"],
    answer: 2,
    fact: "260 goals, and he retired in 2006.",
  },
  {
    id: "f15",
    prompt: "What does a red card mean?",
    choices: [
      "A final warning",
      "The player is sent off",
      "A penalty is awarded",
      "The player must be substituted",
    ],
    answer: 1,
  },
  {
    id: "f16",
    prompt: "Which country does Kylian Mbappé play for?",
    choices: ["Belgium", "France", "Portugal", "Morocco"],
    answer: 1,
  },
  {
    id: "f17",
    prompt: "How many substitutions are most competitions allowed since the 2022 law change?",
    choices: ["3", "4", "5", "6"],
    answer: 2,
  },
  {
    id: "f18",
    prompt: "Who holds the record for most goals in a single Champions League season?",
    choices: ["Lionel Messi", "Robert Lewandowski", "Erling Haaland", "Cristiano Ronaldo"],
    answer: 3,
    fact: "17 in 2013–14, for Real Madrid.",
  },
  {
    id: "f19",
    prompt: "What is a hat-trick?",
    choices: [
      "Three goals by one player in a match",
      "Three assists in a match",
      "Three wins in a row",
      "Three saves from one attack",
    ],
    answer: 0,
  },
  {
    id: "f20",
    prompt: "Which club plays its home games at the Allianz Arena?",
    choices: ["Borussia Dortmund", "Bayern Munich", "RB Leipzig", "Juventus"],
    answer: 1,
  },
  {
    id: "f21",
    prompt: "Which trophy do the winners of the English top flight receive?",
    choices: ["The FA Cup", "The Community Shield", "The Premier League trophy", "The Carabao Cup"],
    answer: 2,
  },
  {
    id: "f22",
    prompt: "Which South American nation won the 2021 and 2024 Copa América?",
    choices: ["Brazil", "Colombia", "Uruguay", "Argentina"],
    answer: 3,
  },
  {
    id: "f23",
    prompt: "How many players from one team start a match on the pitch?",
    choices: ["10", "11", "12", "9"],
    answer: 1,
  },
  {
    id: "f24",
    prompt: "What is the offside rule judged against?",
    choices: [
      "The halfway line",
      "The second-last opponent",
      "The penalty area line",
      "The last defender's back foot only",
    ],
    answer: 1,
    fact: "The goalkeeper usually is the last one, which is why people say \"last defender\".",
  },
];
