import type { Question } from "./types";

export const naruto: readonly Question[] = [
  {
    id: "n1",
    prompt: "What does Naruto want more than anything?",
    choices: [
      "To find his parents",
      "To become Hokage",
      "To leave the village",
      "To defeat Sasuke",
    ],
    answer: 1,
  },
  {
    id: "n2",
    prompt: "Which tailed beast is sealed inside Naruto?",
    choices: ["The One-Tail", "The Eight-Tails", "The Nine-Tails", "The Three-Tails"],
    answer: 2,
    fact: "Kurama, sealed by the Fourth Hokage the night Naruto was born.",
  },
  {
    id: "n3",
    prompt: "Who leads Team 7?",
    choices: ["Might Guy", "Asuma Sarutobi", "Kakashi Hatake", "Iruka Umino"],
    answer: 2,
  },
  {
    id: "n4",
    prompt: "Which clan does Sasuke belong to?",
    choices: ["Hyuga", "Uchiha", "Nara", "Senju"],
    answer: 1,
  },
  {
    id: "n5",
    prompt: "Who wiped out the Uchiha clan?",
    choices: ["Madara Uchiha", "Obito Uchiha", "Itachi Uchiha", "Danzo Shimura"],
    answer: 2,
    fact: "Under orders — which took the series about four hundred episodes to explain.",
  },
  {
    id: "n6",
    prompt: "Which jutsu did Jiraiya teach Naruto?",
    choices: ["Chidori", "Rasengan", "Shadow Clone", "Summoning"],
    answer: 1,
  },
  {
    id: "n7",
    prompt: "Which of the Legendary Sannin became the Fifth Hokage?",
    choices: ["Jiraiya", "Orochimaru", "Tsunade", "Shizune"],
    answer: 2,
  },
  {
    id: "n8",
    prompt: "What is hidden under Kakashi's headband?",
    choices: ["A Byakugan", "A Sharingan", "A scar", "A Rinnegan"],
    answer: 1,
  },
  {
    id: "n9",
    prompt: "What is Naruto's son called?",
    choices: ["Boruto", "Himawari", "Konohamaru", "Shikadai"],
    answer: 0,
  },
  {
    id: "n10",
    prompt: "Who does Naruto marry?",
    choices: ["Sakura Haruno", "Ino Yamanaka", "Hinata Hyuga", "Temari"],
    answer: 2,
  },
  {
    id: "n11",
    prompt: "Which village is Naruto from?",
    choices: ["Hidden Sand", "Hidden Leaf", "Hidden Mist", "Hidden Cloud"],
    answer: 1,
    fact: "Konohagakure — the Village Hidden in the Leaves.",
  },
  {
    id: "n12",
    prompt: "What is the organisation in black cloaks with red clouds called?",
    choices: ["The Akatsuki", "The Anbu", "The Root", "The Kara"],
    answer: 0,
  },
  {
    id: "n13",
    prompt: "What is Rock Lee's speciality?",
    choices: ["Genjutsu", "Ninjutsu", "Taijutsu", "Fuinjutsu"],
    answer: 2,
    fact: "He can't use chakra for anything else, which is the entire point of him.",
  },
  {
    id: "n14",
    prompt: "Who was the Fourth Hokage?",
    choices: ["Hiruzen Sarutobi", "Minato Namikaze", "Tobirama Senju", "Hashirama Senju"],
    answer: 1,
  },
  {
    id: "n15",
    prompt: "Which technique does Sasuke channel lightning into his hand for?",
    choices: ["Chidori", "Amaterasu", "Susanoo", "Rasenshuriken"],
    answer: 0,
  },
  {
    id: "n16",
    prompt: "Which tailed beast is sealed inside Gaara?",
    choices: ["Shukaku, the One-Tail", "Matatabi, the Two-Tails", "Son Goku, the Four-Tails", "Gyuki, the Eight-Tails"],
    answer: 0,
  },
  {
    id: "n17",
    prompt: "What does the Nara clan manipulate?",
    choices: ["Insects", "Shadows", "Minds", "Bones"],
    answer: 1,
  },
  {
    id: "n18",
    prompt: "Which clan has the Byakugan?",
    choices: ["Uchiha", "Aburame", "Hyuga", "Inuzuka"],
    answer: 2,
  },
  {
    id: "n19",
    prompt: "Where did Naruto train to learn Sage Mode?",
    choices: ["Mount Myoboku", "The Valley of the End", "Ryuchi Cave", "Shikkotsu Forest"],
    answer: 0,
    fact: "Home of the toads, and of Jiraiya's summoning contract.",
  },
  {
    id: "n20",
    prompt: "Who is known as the Copy Ninja?",
    choices: ["Might Guy", "Kakashi Hatake", "Yamato", "Sai"],
    answer: 1,
  },
  {
    id: "n21",
    prompt: "What is the name of Naruto's favourite ramen stand?",
    choices: ["Ichiraku", "Yakiniku Q", "Amaguriama", "Sukiyaki-tei"],
    answer: 0,
  },
  {
    id: "n22",
    prompt: "Which animal does Kiba fight alongside?",
    choices: ["A hawk", "A dog", "A monkey", "A slug"],
    answer: 1,
    fact: "Akamaru, who stops being pocket-sized somewhere around Shippuden.",
  },
  {
    id: "n23",
    prompt: "What is the exam that promotes genin to chunin called?",
    choices: ["The Chunin Exams", "The Jonin Trials", "The Academy Finals", "The Kage Summit"],
    answer: 0,
  },
  {
    id: "n24",
    prompt: "Which eye technique is considered the strongest of the three great dojutsu?",
    choices: ["Sharingan", "Byakugan", "Rinnegan", "Tenseigan"],
    answer: 2,
  },
];
