import type { Question } from "./types";

export const onePiece: readonly Question[] = [
  {
    id: "o1",
    prompt: "What does Luffy want to become?",
    choices: [
      "The world's strongest swordsman",
      "King of the Pirates",
      "A Marine admiral",
      "A Yonko",
    ],
    answer: 1,
  },
  {
    id: "o2",
    prompt: "Which Devil Fruit did Luffy eat?",
    choices: ["Gum-Gum Fruit", "Flame-Flame Fruit", "Chop-Chop Fruit", "Rumble-Rumble Fruit"],
    answer: 0,
    fact: "The Gomu Gomu no Mi — stolen from Shanks' crew by accident.",
  },
  {
    id: "o3",
    prompt: "What is the Straw Hats' second ship called?",
    choices: ["Going Merry", "Thousand Sunny", "Red Force", "Oro Jackson"],
    answer: 1,
  },
  {
    id: "o4",
    prompt: "Who is the swordsman of the crew?",
    choices: ["Sanji", "Usopp", "Roronoa Zoro", "Brook"],
    answer: 2,
  },
  {
    id: "o5",
    prompt: "What is Zoro's dream?",
    choices: [
      "To draw a map of the world",
      "To find the All Blue",
      "To become the world's greatest swordsman",
      "To cure every disease",
    ],
    answer: 2,
  },
  {
    id: "o6",
    prompt: "Who cooks for the Straw Hats?",
    choices: ["Sanji", "Chopper", "Franky", "Jinbe"],
    answer: 0,
    fact: "And his own dream is to find the All Blue.",
  },
  {
    id: "o7",
    prompt: "Who was the previous Pirate King?",
    choices: ["Whitebeard", "Gol D. Roger", "Monkey D. Garp", "Silvers Rayleigh"],
    answer: 1,
  },
  {
    id: "o8",
    prompt: "What is Nami's role on the crew?",
    choices: ["Doctor", "Navigator", "Archaeologist", "Shipwright"],
    answer: 1,
  },
  {
    id: "o9",
    prompt: "Who is the ship's doctor?",
    choices: ["Tony Tony Chopper", "Nico Robin", "Brook", "Usopp"],
    answer: 0,
  },
  {
    id: "o10",
    prompt: "What job does Usopp do?",
    choices: ["Sniper", "Helmsman", "Musician", "Cook"],
    answer: 0,
  },
  {
    id: "o11",
    prompt: "Who gave Luffy his straw hat?",
    choices: ["Gol D. Roger", "Shanks", "Garp", "Ace"],
    answer: 1,
    fact: "Roger wore it first. It has been handed down twice.",
  },
  {
    id: "o12",
    prompt: "What was the crew's first ship called?",
    choices: ["Going Merry", "Thousand Sunny", "Baratie", "Sexy Foxy"],
    answer: 0,
  },
  {
    id: "o13",
    prompt: "What is the second half of the Grand Line called?",
    choices: ["The New World", "The Calm Belt", "Paradise", "The Red Line"],
    answer: 0,
  },
  {
    id: "o14",
    prompt: "What can Nico Robin's Devil Fruit do?",
    choices: [
      "Turn her invisible",
      "Sprout copies of her limbs anywhere",
      "Control the weather",
      "Read minds",
    ],
    answer: 1,
    fact: "The Hana Hana no Mi. Hands, eyes, ears — anywhere she can see.",
  },
  {
    id: "o15",
    prompt: "Which of Luffy's brothers died at Marineford?",
    choices: ["Sabo", "Portgas D. Ace", "Koby", "Law"],
    answer: 1,
  },
  {
    id: "o16",
    prompt: "How many types of Haki are there?",
    choices: ["Two", "Three", "Four", "Six"],
    answer: 1,
    fact: "Observation, Armament, and Conqueror's — and only a few can use the last.",
  },
  {
    id: "o17",
    prompt: "What is Franky?",
    choices: ["A fishman", "A cyborg shipwright", "A skeleton", "A giant"],
    answer: 1,
  },
  {
    id: "o18",
    prompt: "What is Brook's job on the crew?",
    choices: ["Musician", "Doctor", "Navigator", "Sniper"],
    answer: 0,
  },
  {
    id: "o19",
    prompt: "Which underwater prison did Luffy break into?",
    choices: ["Impel Down", "Enies Lobby", "Marineford", "Sabaody"],
    answer: 0,
  },
  {
    id: "o20",
    prompt: "Who is the world's strongest swordsman?",
    choices: ["Roronoa Zoro", "Shanks", "Dracule Mihawk", "Vista"],
    answer: 2,
  },
  {
    id: "o21",
    prompt: "What is the dangerous sea route the Straw Hats sail?",
    choices: ["The East Blue", "The Grand Line", "The Calm Belt", "The All Blue"],
    answer: 1,
  },
  {
    id: "o22",
    prompt: "What is the compass that works on the Grand Line called?",
    choices: ["A Log Pose", "An Eternal Compass", "A Sea Chart", "A Vivre Card"],
    answer: 0,
  },
  {
    id: "o23",
    prompt: "What happens to a Devil Fruit user in seawater?",
    choices: [
      "Nothing at all",
      "They lose their strength and sink",
      "Their power doubles",
      "They turn into their fruit",
    ],
    answer: 1,
  },
  {
    id: "o24",
    prompt: "Which Straw Hat joined the crew last, as a former Warlord and fishman?",
    choices: ["Jinbe", "Franky", "Brook", "Robin"],
    answer: 0,
  },
];
