import type { Question } from "./types";

export const pokemon: readonly Question[] = [
  {
    id: "p1",
    prompt: "Which Pokémon is number 001 in the National Pokédex?",
    choices: ["Pikachu", "Bulbasaur", "Charmander", "Squirtle"],
    answer: 1,
  },
  {
    id: "p2",
    prompt: "What type is Pikachu?",
    choices: ["Normal", "Fighting", "Electric", "Psychic"],
    answer: 2,
  },
  {
    id: "p3",
    prompt: "How many Pokémon were there in Generation I?",
    choices: ["100", "150", "151", "251"],
    answer: 2,
    fact: "Mew was the 151st, and was famously not in the original code by accident.",
  },
  {
    id: "p4",
    prompt: "What does Charmander evolve into first?",
    choices: ["Charizard", "Charmeleon", "Flareon", "Magmar"],
    answer: 1,
  },
  {
    id: "p5",
    prompt: "Which villainous team appears in Pokémon Red and Blue?",
    choices: ["Team Aqua", "Team Galactic", "Team Rocket", "Team Plasma"],
    answer: 2,
  },
  {
    id: "p6",
    prompt: "What is Eevee's Fire-type evolution?",
    choices: ["Flareon", "Vaporeon", "Jolteon", "Leafeon"],
    answer: 0,
  },
  {
    id: "p7",
    prompt: "Which Pokémon evolves into Gengar?",
    choices: ["Gastly", "Haunter", "Misdreavus", "Duskull"],
    answer: 1,
  },
  {
    id: "p8",
    prompt: "Which region is Pokémon Scarlet and Violet set in?",
    choices: ["Galar", "Alola", "Paldea", "Kalos"],
    answer: 2,
  },
  {
    id: "p9",
    prompt: "What type is Snorlax?",
    choices: ["Normal", "Fighting", "Ground", "Rock"],
    answer: 0,
  },
  {
    id: "p10",
    prompt: "What is the maximum level a Pokémon can reach?",
    choices: ["50", "99", "100", "255"],
    answer: 2,
  },
  {
    id: "p11",
    prompt: "Which type is completely immune to Normal-type moves?",
    choices: ["Steel", "Rock", "Ghost", "Dark"],
    answer: 2,
    fact: "Which is why Normal attacks whiffed entirely on Gastly in Gen I.",
  },
  {
    id: "p12",
    prompt: "Who is the Pokémon Professor of the Kanto region?",
    choices: ["Professor Elm", "Professor Oak", "Professor Birch", "Professor Rowan"],
    answer: 1,
  },
  {
    id: "p13",
    prompt: "What is Charizard's type combination?",
    choices: ["Fire only", "Fire / Dragon", "Fire / Flying", "Fire / Ground"],
    answer: 2,
    fact: "It is not part Dragon, and it never has been.",
  },
  {
    id: "p14",
    prompt: "Which region is Generation II set in?",
    choices: ["Hoenn", "Johto", "Sinnoh", "Unova"],
    answer: 1,
  },
  {
    id: "p15",
    prompt: "Which of these is one of the Legendary Birds of Kanto?",
    choices: ["Lugia", "Zapdos", "Rayquaza", "Ho-Oh"],
    answer: 1,
    fact: "Articuno, Zapdos and Moltres.",
  },
  {
    id: "p16",
    prompt: "Which Pokémon was cloned from Mew?",
    choices: ["Mewtwo", "Deoxys", "Ditto", "Genesect"],
    answer: 0,
  },
  {
    id: "p17",
    prompt: "Which type is super effective against Water?",
    choices: ["Fire", "Electric", "Flying", "Poison"],
    answer: 1,
    fact: "Grass works too — but Electric is the one on this list.",
  },
  {
    id: "p18",
    prompt: "What does Psyduck evolve into?",
    choices: ["Golduck", "Slowbro", "Politoed", "Ducklett"],
    answer: 0,
  },
  {
    id: "p19",
    prompt: "What is the standard item used to catch a Pokémon?",
    choices: ["A Poké Ball", "A Potion", "A Rare Candy", "An Escape Rope"],
    answer: 0,
  },
  {
    id: "p20",
    prompt: "Which Pokémon can transform into any other Pokémon it sees?",
    choices: ["Zorua", "Ditto", "Mew", "Smeargle"],
    answer: 1,
  },
  {
    id: "p21",
    prompt: "How many badges must you collect in most main-series regions?",
    choices: ["4", "6", "8", "10"],
    answer: 2,
  },
  {
    id: "p22",
    prompt: "Which type was introduced in Generation VI to rebalance Dragons?",
    choices: ["Dark", "Steel", "Fairy", "Ghost"],
    answer: 2,
  },
  {
    id: "p23",
    prompt: "Which Pokémon is the mascot on the cover of Pokémon Red?",
    choices: ["Charizard", "Blastoise", "Mewtwo", "Venusaur"],
    answer: 0,
  },
  {
    id: "p24",
    prompt: "What is the name of the rival organisation's boss in Kanto?",
    choices: ["Giovanni", "Archie", "Cyrus", "Ghetsis"],
    answer: 0,
    fact: "He is also the eighth Gym Leader, which nobody in Viridian seems to mind.",
  },
];
