import type { Question } from "./types";

export const racing: readonly Question[] = [
  {
    id: "r1",
    prompt: "How many Formula 1 titles do Michael Schumacher and Lewis Hamilton each hold?",
    choices: ["5", "6", "7", "8"],
    answer: 2,
  },
  {
    id: "r2",
    prompt: "Which team has won the most F1 Constructors' Championships?",
    choices: ["McLaren", "Ferrari", "Williams", "Red Bull"],
    answer: 1,
  },
  {
    id: "r3",
    prompt: "Which flag is waved at the end of a race?",
    choices: ["The blue flag", "The chequered flag", "The white flag", "The green flag"],
    answer: 1,
  },
  {
    id: "r4",
    prompt: "Which Grand Prix is run on a street circuit through a principality?",
    choices: ["Singapore", "Monaco", "Baku", "Las Vegas"],
    answer: 1,
    fact: "Overtaking there is theoretically legal and practically impossible.",
  },
  {
    id: "r5",
    prompt: "Who won the 2021 Formula 1 drivers' title?",
    choices: ["Lewis Hamilton", "Max Verstappen", "Valtteri Bottas", "Charles Leclerc"],
    answer: 1,
    fact: "On the last lap of the last race, which people are still arguing about.",
  },
  {
    id: "r6",
    prompt: "What does DRS stand for?",
    choices: [
      "Drag Reduction System",
      "Direct Response Steering",
      "Dynamic Ride Setting",
      "Downforce Regulation System",
    ],
    answer: 0,
  },
  {
    id: "r7",
    prompt: "Which country is Ferrari from?",
    choices: ["France", "Germany", "Italy", "Spain"],
    answer: 2,
  },
  {
    id: "r8",
    prompt: "Which French endurance race lasts a full day and night?",
    choices: ["The Nürburgring 24", "The 24 Hours of Le Mans", "The Spa 24", "The Daytona 24"],
    answer: 1,
  },
  {
    id: "r9",
    prompt: "Which American race is held every Memorial Day weekend?",
    choices: ["The Daytona 500", "The Indianapolis 500", "The Coca-Cola 600", "The Brickyard 400"],
    answer: 1,
  },
  {
    id: "r10",
    prompt: "What does a yellow flag mean?",
    choices: [
      "Danger ahead — slow down, no overtaking",
      "The race is over",
      "You are being lapped",
      "Return to the pits",
    ],
    answer: 0,
  },
  {
    id: "r11",
    prompt: "Which team does Max Verstappen drive for?",
    choices: ["Mercedes", "Red Bull Racing", "Aston Martin", "Alpine"],
    answer: 1,
  },
  {
    id: "r12",
    prompt: "How many different dry tyre compounds must a driver use in a dry F1 race?",
    choices: ["1", "2", "3", "4"],
    answer: 1,
  },
  {
    id: "r13",
    prompt: "Which circuit hosts the Italian Grand Prix?",
    choices: ["Imola", "Mugello", "Monza", "Misano"],
    answer: 2,
    fact: "The Temple of Speed — the fastest average lap on the calendar.",
  },
  {
    id: "r14",
    prompt: "What nationality was Ayrton Senna?",
    choices: ["Argentine", "Brazilian", "Portuguese", "Colombian"],
    answer: 1,
  },
  {
    id: "r15",
    prompt: "How many points does the winner of an F1 Grand Prix score?",
    choices: ["10", "18", "25", "30"],
    answer: 2,
  },
  {
    id: "r16",
    prompt: "What is pole position?",
    choices: [
      "Starting first on the grid",
      "The fastest lap of the race",
      "The last place on the grid",
      "The pit lane entry",
    ],
    answer: 0,
  },
  {
    id: "r17",
    prompt: "Which manufacturer has won the 24 Hours of Le Mans the most times?",
    choices: ["Audi", "Ferrari", "Porsche", "Toyota"],
    answer: 2,
    fact: "Nineteen overall wins, the first in 1970.",
  },
  {
    id: "r18",
    prompt: "What is NASCAR's most prestigious race?",
    choices: ["The Daytona 500", "The Southern 500", "The Bristol Night Race", "The Talladega 500"],
    answer: 0,
  },
  {
    id: "r19",
    prompt: "Which F1 team is based in Woking, England?",
    choices: ["Williams", "McLaren", "Aston Martin", "Haas"],
    answer: 1,
  },
  {
    id: "r20",
    prompt: "Which driver is nicknamed The Iceman?",
    choices: ["Kimi Räikkönen", "Mika Häkkinen", "Nico Rosberg", "Valtteri Bottas"],
    answer: 0,
  },
  {
    id: "r21",
    prompt: "In rallying, what is the co-driver's main job?",
    choices: [
      "Reading the pace notes",
      "Changing the tyres",
      "Steering on hairpins",
      "Operating the handbrake",
    ],
    answer: 0,
  },
  {
    id: "r22",
    prompt: "What is the black-and-orange circle flag shown to a driver for?",
    choices: [
      "A mechanical problem — pit immediately",
      "A drive-through penalty",
      "Unsportsmanlike driving",
      "The final lap",
    ],
    answer: 0,
  },
  {
    id: "r23",
    prompt: "Which racing series uses only electric single-seaters?",
    choices: ["IndyCar", "Formula E", "Formula 2", "Super Formula"],
    answer: 1,
  },
  {
    id: "r24",
    prompt: "Roughly how long does a well-executed modern F1 pit stop take?",
    choices: ["Under 3 seconds", "About 6 seconds", "About 10 seconds", "About 15 seconds"],
    answer: 0,
    fact: "The record sits a shade under two seconds.",
  },
];
