import type { Question } from "./types";

export const wwe: readonly Question[] = [
  {
    id: "w1",
    prompt: "What is The Rock's real name?",
    choices: ["Dwayne Johnson", "Mark Calaway", "Paul Levesque", "Michael Hickenbottom"],
    answer: 0,
  },
  {
    id: "w2",
    prompt: "Which annual event is billed as WWE's biggest show of the year?",
    choices: ["SummerSlam", "Royal Rumble", "WrestleMania", "Survivor Series"],
    answer: 2,
  },
  {
    id: "w3",
    prompt: "Which wrestler is known as The Deadman?",
    choices: ["Kane", "The Undertaker", "Sting", "Bray Wyatt"],
    answer: 1,
  },
  {
    id: "w4",
    prompt: "How long was The Undertaker's WrestleMania winning streak?",
    choices: ["17–0", "19–0", "21–0", "25–0"],
    answer: 2,
  },
  {
    id: "w5",
    prompt: "Who ended The Undertaker's WrestleMania streak?",
    choices: ["Roman Reigns", "Brock Lesnar", "Triple H", "Shawn Michaels"],
    answer: 1,
    fact: "WrestleMania 30, and nobody in the building believed it.",
  },
  {
    id: "w6",
    prompt: "Complete the catchphrase: \"Austin 3:__\"",
    choices: ["3:14", "3:15", "3:16", "3:17"],
    answer: 2,
  },
  {
    id: "w7",
    prompt: "Who is billed as The Beast Incarnate?",
    choices: ["Brock Lesnar", "Goldberg", "Braun Strowman", "Bobby Lashley"],
    answer: 0,
  },
  {
    id: "w8",
    prompt: "Which catchphrase belongs to John Cena?",
    choices: ["You can't see me", "Rest in peace", "It's clobberin' time", "Woo!"],
    answer: 0,
  },
  {
    id: "w9",
    prompt: "In which match do wrestlers climb a ladder to grab a hanging briefcase?",
    choices: ["Hell in a Cell", "TLC", "Money in the Bank", "Elimination Chamber"],
    answer: 2,
    fact: "The briefcase is a title shot, cashable any time for a year.",
  },
  {
    id: "w10",
    prompt: "How many entrants are there in a traditional Royal Rumble match?",
    choices: ["20", "24", "30", "40"],
    answer: 2,
  },
  {
    id: "w11",
    prompt: "Who calls himself the Head of the Table?",
    choices: ["Seth Rollins", "Roman Reigns", "Cody Rhodes", "Drew McIntyre"],
    answer: 1,
  },
  {
    id: "w12",
    prompt: "What is Rey Mysterio's signature move called?",
    choices: ["The 450", "The 619", "The 630", "The 450 Splash"],
    answer: 1,
    fact: "Named after the area code for San Diego.",
  },
  {
    id: "w13",
    prompt: "What was WWE called before 2002?",
    choices: ["WCW", "ECW", "WWF", "NWA"],
    answer: 2,
    fact: "A lawsuit from the World Wildlife Fund forced the change.",
  },
  {
    id: "w14",
    prompt: "Who is the Rated-R Superstar?",
    choices: ["Edge", "Christian", "CM Punk", "Randy Orton"],
    answer: 0,
  },
  {
    id: "w15",
    prompt: "What is Randy Orton's finishing move?",
    choices: ["The Pedigree", "The RKO", "The Stunner", "The F5"],
    answer: 1,
  },
  {
    id: "w16",
    prompt: "Which wrestler is nicknamed The Viper?",
    choices: ["Jake Roberts", "Randy Orton", "Kevin Owens", "Seth Rollins"],
    answer: 1,
  },
  {
    id: "w17",
    prompt: "Who declared herself The Man?",
    choices: ["Charlotte Flair", "Bayley", "Becky Lynch", "Sasha Banks"],
    answer: 2,
  },
  {
    id: "w18",
    prompt: "What is Triple H's real name?",
    choices: ["Paul Levesque", "Paul Wight", "Paul Heyman", "Phil Brooks"],
    answer: 0,
  },
  {
    id: "w19",
    prompt: "Whose finisher is the Tombstone Piledriver?",
    choices: ["Kane", "The Undertaker", "The Big Show", "Umaga"],
    answer: 1,
  },
  {
    id: "w20",
    prompt: "What is the name of WWE's developmental brand?",
    choices: ["NXT", "ECW", "205 Live", "Main Event"],
    answer: 0,
  },
  {
    id: "w21",
    prompt: "Which wrestler is known as the Nature Boy, famous for the strut and the \"Woo!\"?",
    choices: ["Dusty Rhodes", "Ric Flair", "Roddy Piper", "Randy Savage"],
    answer: 1,
  },
  {
    id: "w22",
    prompt: "Which two brands did WWE split its roster into in the 2002 draft?",
    choices: ["Raw and SmackDown", "Raw and NXT", "SmackDown and ECW", "Raw and Heat"],
    answer: 0,
  },
  {
    id: "w23",
    prompt: "What is CM Punk's famous 2011 monologue known as?",
    choices: ["The Shoot", "The Pipe Bomb", "The Manifesto", "The Promo"],
    answer: 1,
  },
  {
    id: "w24",
    prompt: "Which stable did Roman Reigns, Seth Rollins and Dean Ambrose form in 2012?",
    choices: ["The Nexus", "Evolution", "The Shield", "The Wyatt Family"],
    answer: 2,
  },
];
